"""add source field to users

Revision ID: 05e8a1ff35f6
Revises: 7df3a9711567
Create Date: 2025-10-18 18:37:52.069167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e8a1ff35f6'
down_revision: Union[str, Sequence[str], None] = '7df3a9711567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source')
    # ### end Alembic commands ###
