"""delete relationship with user

Revision ID: 7811e971e0e4
Revises: aa6c5cbb5e8a
Create Date: 2025-10-25 09:34:07.499316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7811e971e0e4'
down_revision: Union[str, Sequence[str], None] = 'aa6c5cbb5e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
