"""add currency_notify_time to user

Revision ID: 7df3a9711567
Revises: 01280af7b86e
Create Date: 2025-09-22 01:01:45.321080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df3a9711567'
down_revision: Union[str, Sequence[str], None] = '01280af7b86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency_notify_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency_notify_time')
    # ### end Alembic commands ###
