"""add referrals table and referral_id to users

Revision ID: aa6c5cbb5e8a
Revises: 05e8a1ff35f6
Create Date: 2025-10-25 09:30:24.046596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6c5cbb5e8a'
down_revision: Union[str, Sequence[str], None] = '05e8a1ff35f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('users', sa.Column('referral_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'referrals', ['referral_id'], ['id'])
    op.drop_column('users', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referral_id')
    op.drop_table('referrals')
    # ### end Alembic commands ###
