from ..database.crud import get_user_data

LANGS = {
    'ru': {
        'welcome': 'Добро пожаловать в QarzNazoratBot!\nВыберите действие:',
        'choose_action': 'Выберите действие:',
        'add_debt': '➕ Добавить долг',
        'my_debts': '📄 Мои долги',
        'clear_all': '🕔 Очистить все',
        'reminders_menu': '⏰ Мои напоминания',
        'change_lang': '🌐 Сменить язык',
        'choose_lang': 'Выберите язык:',
        'lang_ru': 'Русский',
        'lang_uz': 'Узбекский',
        'no_debts': 'У вас нет долгов.',
        'your_debts': 'Ваши долги:',
        'debt_saved': '✅ Долг записан!\n\nВыберите действие:',
        'debt_closed': '✅ Долг отмечен как возвращён!\n\nВыберите действие:',
        'debt_deleted': '❌ Долг удалён!\n\nВыберите действие:',
        'debt_not_found': 'Долг не найден',
        'confirm_close': 'Вы уверены, что хотите отметить долг как возвращён?',
        'confirm_del': 'Вы уверены, что хотите удалить долг?',
        'cancelled': 'Действие отменено.',
        'back': '⬅️ Назад',
        'to_menu': 'В меню',
        'to_list': '⬅️ К списку',
        'edit': 'Изменить',
        'delete': 'Удалить',
        'close': 'Погасить',
        'extend': 'Продлить',
        'person': '📛 Имя человека:',
        'currency': 'Выберите валюту:',
        'amount': '💰 Сумма:',
        'amount_wrong': 'Введите сумму числом!',
        'due': '📅 Срок возврата (например):\n{suggest_date}',
        'due_wrong': 'Формат даты (например):\n{suggest_date}',
        'direction': '🔁 Ты дал или взял?',
        'dir_gave': 'Ты дал',
        'dir_took': 'Ты взял',
        'comment': '📝 Комментарий (можно пропустить):',
        'skip_comment': 'Пропустить',
        'date_format': 'Формат даты: {suggest_date}',
        'date_changed': 'Дата изменена!',
        'changed': 'Изменено!',
        'all_deleted': '🕔 Все долги удалены!\n\nВыберите действие:',
        'clear_all_confirm': 'Вы точно хотите удалить все долги?',
        'yes': 'Да',
        'no': 'Нет',
        'notify_time': 'Введите новое время для напоминаний (например: 09:00):',
        'notify_wrong': 'Некорректный формат времени. Введите в формате ЧЧ:ММ, например 09:00',
        'notify_set': 'Время напоминаний установлено!\n',
        'edit_what': 'Что изменить?',
        'debt_card': '{person} {amount} {currency}\nСрок: {due}\nКомментарий: {comment}\nВремя напоминания: {notify_time}',
        'editfield_person': 'Введите новое имя:',
        'editfield_amount': 'Введите новую сумму (только число):',
        'editfield_currency': 'Введите новую валюту (USD, UZS, EUR):',
        'editfield_due': 'Введите новую дату (например: {suggest_date}):',
        'editfield_comment': 'Введите новый комментарий:',
        'currency_changed': 'Валюта изменена!',
        'remind_close': '✅ Погасить',
        'remind_extend': '🔁 Продлить',
        'remind_delete': '❌ Удалить',
        'action_close': '✅ Погасить',
        'action_delete': '❌ Удалить',
        'action_extend': '🔁 Продлить',
        'direction_wrong': 'Введите "gave" или "took"!',
        'reminder_time': 'Ваше время напоминания: {time}',
        'reminder_change': 'Изменить время',
        'forward': 'Вперёд ➡️',
        'backward': '⬅️ Назад',
        'db_error': 'Ошибка при обращении к базе данных. Попробуйте позже.',
        'not_found_or_no_access': 'Долг не найден или нет доступа.',
        'delete_error': 'Ошибка при удалении долга.',
        'update_error': 'Ошибка при обновлении долга.',
        'save_notify_error': 'Ошибка при сохранении времени уведомлений.',
        'bad_request': 'Ошибка: неверный формат запроса.',
        'editfield_due_btn': 'Изменить дату',
        'editfield_person_btn': 'Изменить имя',
        'editfield_amount_btn': 'Изменить сумму',
        'editfield_currency_btn': 'Изменить валюту',
        'editfield_due_btn': 'Изменить дату',
        'editfield_comment_btn': 'Изменить комментарий',
        'how_to_use_btn': 'ℹ️ Как пользоваться',
        'how_to_use_msg': 'Нажмите кнопку ниже, чтобы открыть подробную инструкцию по использованию бота.',
        'open_instruction': 'Открыть инструкцию',
        'continue_instruction': 'Продолжить инструкцию',
        'instruction_back': '⬅️ Назад',
    },
    'uz': {
        'welcome': 'QarzNazoratBot-ga xush kelibsiz!\nAmalni tanlang:',
        'choose_action': 'Amalni tanlang:',
        'add_debt': '➕ Qarzni qo‘shish',
        'my_debts': '📄 Qarzlarim',
        'clear_all': '🕔 Hammasini o‘chirish',
        'reminders_menu': '⏰ Eslatmalarim',
        'change_lang': '🌐 Tilni o‘zgartirish',
        'choose_lang': 'Tilni tanlang:',
        'lang_ru': 'Rus tili',
        'lang_uz': 'O‘zbek tili',
        'no_debts': 'Sizda qarzlar yo‘q.',
        'your_debts': 'Qarzlaringiz:',
        'debt_saved': '✅ Qarz saqlandi!\n\nAmalni tanlang:',
        'debt_closed': '✅ Qarz yopildi!\n\nAmalni tanlang:',
        'debt_deleted': '❌ Qarz o‘chirildi!\n\nAmalni tanlang:',
        'debt_not_found': 'Qarz topilmadi',
        'confirm_close': 'Qarz yopildi deb belgilansinmi?',
        'confirm_del': 'Qarz o‘chirilsinmi?',
        'cancelled': 'Amal bekor qilindi.',
        'back': '⬅️ Orqaga',
        'to_menu': 'Menyuga',
        'to_list': '⬅️ Ro‘yxatga',
        'edit': 'O‘zgartirish',
        'delete': 'O‘chirish',
        'close': 'Yopish',
        'extend': 'Uzaytirish',
        'person': '📛 Kimdan qarz?:',
        'currency': 'Valyutani tanlang:',
        'amount': '💰 Miqdor:',
        'amount_wrong': 'Miqdor faqat raqam bo‘lishi kerak!',
        'due': '📅 Qaytarish muddati (masalan):\n{suggest_date}',
        'due_wrong': 'Sana formati (masalan):\n{suggest_date}',
        'direction': '🔁 Siz berdingizmi yoki oldingizmi?',
        'dir_gave': 'Siz berdingiz',
        'dir_took': 'Siz oldingiz',
        'comment': '📝 Izoh (ixtiyoriy):',
        'skip_comment': 'O‘tkazib yuborish',
        'date_format': 'Sana formati: {suggest_date}',
        'date_changed': 'Sana o‘zgartirildi!',
        'changed': 'O‘zgartirildi!',
        'all_deleted': '🕔 Barcha qarzlar o‘chirildi!\n\nAmalni tanlang:',
        'clear_all_confirm': 'Barcha qarzlarni o‘chirilsinmi?',
        'yes': 'Ha',
        'no': 'Yo‘q',
        'notify_time': 'Eslatma vaqti (masalan: 09:00):',
        'notify_wrong': 'Vaqt formati noto‘g‘ri. Masalan: 09:00',
        'notify_set': 'Eslatma vaqti o‘rnatildi!\n',
        'edit_what': 'Nimani o‘zgartirasiz?',
        'debt_card': '{person} {amount} {currency}\nSana: {due}\nIzoh: {comment}\nEslatma vaqti: {notify_time}',
        'editfield_person': 'Yangi ismni kiriting:',
        'editfield_amount': 'Yangi miqdorini kiriting:',
        'editfield_currency': 'Yangi valyutani kiriting (USD, UZS, EUR):',
        'editfield_due': 'Yangi muddatni kiriting (masalan: {suggest_date}):',
        'editfield_comment': 'Yangi izohni kiriting:',
        'currency_changed': 'Valyuta o‘zgartirildi!',
        'remind_close': '✅ Yopish',
        'remind_extend': '🔁 Uzaytirish',
        'remind_delete': '❌ O‘chirish',
        'action_close': '✅ Yopish',
        'action_delete': '❌ O‘chirish',
        'action_extend': '🔁 Uzaytirish',
        'direction_wrong': 'Vedite "gave" ili "took"!',
        'reminder_time': 'Eslatma vaqti: {time}',
        'reminder_change': 'Vaqtni o‘zgartirish',
        'forward': 'Oldinga ➡️',
        'backward': '⬅️ Orqaga',
        'db_error': 'Maʼlumotlar bazasiga murojaat qilishda xatolik. Keyinroq urinib ko‘ring.',
        'not_found_or_no_access': 'Qarz topilmadi yoki ruxsat yo‘q.',
        'delete_error': 'Qarz o‘chirishda xatolik.',
        'update_error': 'Qarzni yangilashda xatolik.',
        'save_notify_error': 'Eslatma vaqtini saqlashda xatolik.',
        'bad_request': 'Xatolik: noto‘g‘ri so‘rov formati.',
        'editfield_due_btn': 'Sanani o‘zgartirish',
        'editfield_person_btn': 'Ismni o‘zgartirish',
        'editfield_amount_btn': 'Miqdorni o‘zgartirish',
        'editfield_currency_btn': 'Valyutani o‘zgartirish',
        'editfield_due_btn': 'Sanani o‘zgartirish',
        'editfield_comment_btn': 'Izohni o‘zgartirish',
        'how_to_use_btn': 'ℹ️ Qanday foydalanish',
        'how_to_use_msg': 'Botdan foydalanish bo‘yicha batafsil yo‘riqnomani ochish uchun pastdagi tugmani bosing.',
        'open_instruction': 'Yo‘riqnomani ochish',
        'continue_instruction': 'Yo‘riqnomani davom ettirish',
        'instruction_back': '⬅️ Orqaga',
    }
}

async def tr(user_id: int, key: str, **kwargs) -> str:
    """Получить переведенный текст для пользователя"""
    try:
        user_data = await get_user_data(user_id)
        lang = user_data.get('lang', 'ru')
        text = LANGS[lang].get(key, key)
        return text.format(**kwargs) if kwargs else text
    except Exception:
        # В случае ошибки возвращаем русский текст
        text = LANGS['ru'].get(key, key)
        return text.format(**kwargs) if kwargs else text