from ..database.crud import get_user_data

LANGS = {
    'ru': {
        'welcome': 'Добро пожаловать в QarzNazoratBot!\nВыберите действие:',
        'choose_action': 'Выберите действие:',
        'add_debt': '➕ Добавить долг',
        'my_debts': '📋 Мои долги',
        'clear_all': '🧹 Очистить всё',
        'reminders_menu': '🔔 Напоминания',
        'statistics': '📊 Статистика',
        'currency_rates': '💱 Курс валют',
        'settings': '⚙️ Настройки',
        'help': 'ℹ️ Помощь',
        'change_lang': '🌍 Сменить язык',
        'choose_lang': 'Выберите язык:',
        'lang_ru': 'Русский',
        'lang_uz': 'Узбекский',
        'no_debts': 'У вас нет долгов.',
        "cancel_btn": "❌ Отмена",
        'your_debts': 'Ваши долги:',
        'debt_saved': '✅ Долг записан!\n\nВыберите действие:',
        'debt_closed': '✅ Долг отмечен как возвращён!\n\nВыберите действие:',
        'debt_deleted': '❌ Долг удалён!\n\nВыберите действие:',
        'debt_not_found': 'Долг не найден',
        'confirm_close': 'Вы уверены, что хотите отметить долг как возвращён?',
        'export_excel': '📊 Экспорт в Excel',
        'confirm_del': 'Вы уверены, что хотите удалить долг?',
        'cancelled': 'Действие отменено.',
        'back': '⬅️ Назад',
        'to_menu': 'В меню',
        'to_list': '⬅️ К списку',
        'edit': '✏️ Изменить',
        'delete': '❌ Удалить',
        'close': 'Погасить',
        'extend': 'Продлить',
        'person': '📛 Имя человека:',
        'currency': 'Выберите валюту:',
        'amount': '💰 Сумма:',
        'amount_wrong': 'Введите сумму числом!',
        'due': '📅 Срок возврата (например):\n{suggest_date}',
        'due_wrong': 'Формат даты (например):\n{suggest_date}',
        'direction': '🔁 Ты дал или взял?',
        'dir_gave': 'Ты дал',
        'dir_took': 'Ты взял',
        'comment': '📝 Комментарий (можно пропустить):',
        'skip_comment': 'Пропустить',
        'date_format': 'Формат даты: {suggest_date}',
        'date_changed': 'Дата изменена!',
        'changed': 'Изменено!',
        'all_deleted': '🧹 Все долги удалены!\n\nВыберите действие:',
        'clear_all_confirm': 'Вы точно хотите удалить все долги?',
        'yes': 'Да',
        'no': 'Нет',
        'notify_time': 'Введите новое время для напоминаний (например: 09:00):',
        'notify_wrong': 'Некорректный формат времени. Введите в формате ЧЧ:ММ, например 09:00',
        'notify_set': 'Время напоминаний установлено!\n',
        'edit_what': 'Что изменить?',
        'debt_card': '{person} {amount} {currency}\nСрок: {due}\nКомментарий: {comment}\nВремя напоминания: {notify_time}',
        'editfield_person': 'Введите новое имя:',
        'editfield_amount': 'Введите новую сумму (только число):',
        'editfield_currency': 'Введите новую валюту (USD, UZS, EUR):',
        'editfield_due': 'Введите новую дату (например: {suggest_date}):',
        'editfield_comment': 'Введите новый комментарий:',
        'currency_changed': 'Валюта изменена!',
        'remind_close': '✅ Погасить',
        'remind_extend': '🔁 Продлить',
        'remind_delete': '❌ Удалить',
        'action_close': '✅ Погасить',
        'action_delete': '❌ Удалить',
        'action_extend': '🔁 Продлить',
        'direction_wrong': 'Введите "gave" или "took"!',
        'reminder_time': 'Ваше время напоминания: {time}',
        'reminder_change': 'Изменить время',
        'forward': 'Вперёд ➡️',
        'backward': '⬅️ Назад',
        'db_error': 'Ошибка при обращении к базе данных. Попробуйте позже.',
        'not_found_or_no_access': 'Долг не найден или нет доступа.',
        'delete_error': 'Ошибка при удалении долга.',
        'update_error': 'Ошибка при обновлении долга.',
        'save_notify_error': 'Ошибка при сохранении времени уведомлений.',
        'bad_request': 'Ошибка: неверный формат запроса.',
        'editfield_due_btn': 'Изменить дату',
        'editfield_person_btn': 'Изменить имя',
        'editfield_amount_btn': 'Изменить сумму',
        'editfield_currency_btn': 'Изменить валюту',
        'editfield_comment_btn': 'Изменить комментарий',
        'how_to_use_btn': 'ℹ️ Как пользоваться',
        'how_to_use_msg': 'Нажмите кнопку ниже, чтобы открыть подробную инструкцию по использованию бота.',
        'open_instruction': 'Открыть инструкцию',
        'continue_instruction': 'Продолжить инструкцию',
        'instruction_back': '⬅️ Назад',
        'debt_card_owed': '👤 Должник: {person}\n💰 Сумма долга: {amount} {currency}\n📅 Срок оплаты: {due}\n📝 Комментарий: {comment}\n⏰ Напоминание: {notify_time}',
        'debt_card_owe': '👤 Кому должен: {person}\n💰 Сумма: {amount} {currency}\n📅 Срок оплаты: {due}\n📝 Комментарий: {comment}\n⏰ Напоминание: {notify_time}',
        'daily_reminder_header': '⏰ Напоминание о долгах:',
        'overdue': '⚠️ Просрочен на {days} дн.',
        'due_today': '🔥 Срок истекает сегодня!',
        'due_in_days': '⏳ Осталось {days} дн.',
        'debtor_name': 'Должник {person}',
        'creditor_name': 'Кредитор {person}',
        'single_reminder': '⏰ Напоминание!\n\n{person} должен вернуть {amount} {currency}\nСрок: {due}',
        'multiple_reminders': '⏰ У вас {count} напоминаний о долгах:',
        'process_interrupted': 'Вы хотите продолжить процесс создания?',
        'continue_process': '📝 Продолжить',
        'cancel_and_menu': '🔙 Отменить и в меню',
        'date_in_past': '❌ Указанная дата уже прошла. Пожалуйста, выберите будущую дату.',
        'process_cancelled': '❌ Процесс был отменён. Действие не завершено.',
        'continue_edit': 'Продолжить редактирование',
        'text_only_please': 'Только текст, пожалуйста',
        'export_excel_btn': '📊 Экспорт в Excel',
        'export_loading': '⏳ Подготавливаю экспорт данных...',
        'export_success_caption': '📊 Экспорт завершен успешно!\n\n📝 Файл содержит:\n• Все активные долги\n• Информацию о должниках/кредиторах\n• Суммы и валюты\n• Даты и комментарии\nhttps://telegra.ph/Kak-ispravit-oshibku-pri-otkrytii-fajla-Exel-10-03',
        'export_error': '❌ Ошибка при экспорте данных. Попробуйте позже.',
        'back_main_btn': '🏠 Главное меню',
        "export_col_id": "ID",
        "export_col_person": "Имя",
        "export_col_amount": "Сумма",
        "export_col_currency": "Валюта",
        "export_col_type": "Тип долга",
        "export_col_date": "Дата создания",
        "export_col_due": "Срок погашения",
        "export_col_comment": "Комментарий",
        "export_col_status": "Статус",
        "export_col_created": "Создан",
        "export_type_owe": "Я должен",
        "export_type_owed": "Мне должны",
        "export_status_closed": "Закрыт",
        "export_status_active": "Активен",
        "export_sheet_name": "Долги",
        "add_reminder_btn": "Добавить напоминание",
        "menu.debts_off": "❌ Напоминания о долгах выключены",
        "menu.currency_on": "✅ Курс валют ежедневно в {time}",
        "menu.currency_off": "❌ Напоминания о курсе валют выключены",

        # Новые ключи для напоминаний
        'debts_list': 'Долги',
        'ai_debt_add': '🤖 Добавить долг через ИИ',
        'debt_reminders': '📥 Долги',
        'currency_reminders': '💱 Курс валют',
        'add_reminder': '➕ Добавить напоминание',
        'my_reminders': '📋 Мои напоминания',
        'enable_reminders': '⏰ Включить напоминания',
        'disable_reminders': '❌ Выключить напоминания',
        'setup_time': '⚙ Настроить время',
        'enable_morning_rates': '⏰ Включить курс валют утром',
        'enable_evening_rates': '⏰ Включить курс валют вечером',
        'disable_currency_rates': '❌ Выключить курс валют',
        'no_repeat': '❌ Нет',
        'daily_repeat': '📅 Каждый день',
        'monthly_repeat': '📆 Каждый месяц',
        'reminders_list': 'Напоминания',
        'edit_reminder_text': 'Изменить текст напоминания',
        'edit_reminder_datetime': 'Изменить дату и время',
        'edit_reminder_repeat': 'Изменить повторение',
        'reminder_text_prompt': 'О чём напомнить?',
        'reminder_datetime_prompt': 'Когда напомнить? (например: 25.09 в 19:00)',
        'reminder_repeat_prompt': 'Повторять напоминание?',
        'reminder_created': '✅ Напоминание создано!\n📌 Текст: {text}\n🕒 Дата: {datetime}\n🔁 Повтор: {repeat}',
        'reminder_status_active': '✅ Напоминание долгов в {time}',
        'reminder_status_currency_morning': '✅ Курс валют ежедневно в 7:00',
        'reminder_status_currency_evening': '✅ Курс валют ежедневно в 17:00',
        'reminder_status_disabled': '❌ Напоминания отключены',
        'your_reminders': 'Ваши напоминания:',
        'reminder_deleted': '❌ Напоминание удалено!',
        'reminder_updated': '✅ Напоминание обновлено!',
        'currency_error': '❌ Ошибка получения курсов валют. Попробуйте позже.',
        'currency_format_error': '❌ Ошибка форматирования курсов валют.',
        "start_add": "Введите текст напоминания:",
        "ask_due": "Введите дату и время (формат: 2025-09-22 10:00)",
        "bad_due": "❌ Неверный формат. Попробуйте ещё раз: 2025-09-22 10:00",
        "ask_repeat": "Выберите режим повтора:",
        "created": "✅ Напоминание создано!",
        "no_reminders": "У вас пока нет активных напоминаний.",
        "list_title": "📋 Ваши напоминания:",
        "del_usage": "Использование: /del_reminder <id>",
        "deleted": "🗑 Напоминание {id} удалено.",
        "reminder_message": "Напоминание: {reminder}",
        "currency_message": "{base}/{quote} = {rate:.2f}",

        # --- Repeat buttons ---
        "repeat_none": "Без повтора",
        "repeat_daily": "Ежедневно",
        "repeat_monthly": "Ежемесячно",
        "debts_btn": "Долги",
        "currency_btn": "Курс валют",
        "my_reminders_btn": "Мои напоминания",
        "back_btn": "Назад",

        # Статусы в главном меню Напоминаний
        "debt_reminder_status": "Напоминание долгов в (ваше время)",
        "currency_reminder_status": "Курс валют ежедневно в 7:00",

        # Подменю «Напоминания о долгах»
        "debt_reminders_text": "Автоматические напоминание долгов(за 3 дня, ежедневно, если заём просрочен).",
        "enable_debt": "Включить напоминания",
        "disable_debt": "Выключить напоминания",
        "set_time": "Настроить время",

        # Подменю «Напоминания о курсе валют»
        "currency_reminders_text": "Например, курс доллара каждый день в 7:00.",
        "enable_currency_morning": "Включить курс валют утром (7:00)",
        "enable_currency_evening": "Включить курс валют вечером (17:00)",
        "disable_currency": "Выключить курс валют",
        'ai_debt_input_hint': (
            "Введите данные свободным текстом:\n"
            "- направление ('я должен' или 'мне должны')\n"
            "- контрагент (имя/название)\n"
            "- сумма и валюта (например: 250 USD)\n"
            "- срок (YYYY-MM-DD)\n"
            "- описание (необязательно)"
        ),
        'ai_main_menu': '🔙 Главное меню',
        'ai_parse_failed': 'Не удалось распознать данные. Попробуйте сформулировать проще.',
        'ai_parse_failed_hint': (
            "Не удалось распознать данные. Попробуйте написать проще:\n"
            "я должен Ивану 100 USD до YYYY-MM-DD"
        ),
        'ai_debt_saved': (
            "✅ Долг записан:\n"
            "- Контрагент: {person}\n"
            "- Сумма: {amount} {currency}\n"
            "- Срок: {due}\n"
            "- Направление: {direction}\n"
            "- Комментарий: {comment}"
        ),
        'ai_debt_save_error': '❌ Ошибка при сохранении долга',
        "enter_amount":"Введите сумму для конвертации:",
        "updated":"🕐 Обновлено:",
        "invalid_number_prompt":"❌ Введите число, например: 1000",
        "conversion_error": "❌ Не удалось выполнить конвертацию. Попробуйте позже.",
    },
    'uz': {
        "edit_reminder_text": "Eslatma matnini o'zgartirish",
        "enter_amount": "Konvertatsiya qilish uchun summani kiriting:",
        "conversion_error": "❌ Konvertatsiya bajarilmadi. Iltimos, keyinroq urinib ko'ring.",
        "updated":"🕐 Yangilandi:",
        "invalid_number_prompt":"❌ Raqam kiriting, masalan: 1000",
        "reminder_deleted": "❌ Eslatma o'chirildi!",
        'ai_debt_save_error': '❌ Qarzni saqlashda xatolik yuz berdi',
        "reminder_updated": "✅ Eslatma yangilandi!",
        "reminder_created": "✅ Eslatma yaratildi!\n📌 Matn: {text}\n🕒 Sana: {datetime}\n🔁 Takrorlash: {repeat}",
        "back_btn": "⬅️ Orqaga",
        "welcome": "QarzNazoratBot-ga xush kelibsiz!\nAmalni tanlang:",
        "choose_action": "Amalni tanlang:",
        "add_debt": "➕ Qarzni qo'shish",
        'ai_debt_add': '🤖 Qarzni AI bilan qo shish',
        'ai_debt_saved': (
            "✅ Qarz saqlandi:\n"
            "- Qarzdor: {person}\n"
            "- Summasi: {amount} {currency}\n"
            "- Muddat: {due}\n"
            "- Yo'nalish: {direction}\n"
            "- Izoh: {comment}"
        ),
        'ai_parse_failed_hint': (
            "Ma'lumotlarni aniqlab bo'lmadi. Iltimos, soddaroq yozing:\n"
            "men Ivan ismli odamga YYYY-MM-DD sanasigacha 100 USD qarzdorman"
        ),
        "my_debts": "📋 Qarzlarim",
        "clear_all": "🧹 Hammasini o'chirish",
        "reminders_menu": "🔔 Eslatmalar",
        "statistics": "📊 Statistika",
        "currency_rates": "💱 Valyuta kursi",
        "settings": "⚙️ Sozlamalar",
        "help": "ℹ️ Yordam",
        "change_lang": "🌍 Tilni o'zgartirish",
        'ai_parse_failed': 'Ma lumotlarni aniqlab bo lmadi. Iltimos, soddaroq shaklda yozib ko ring.',
        "choose_lang": "Tilni tanlang:",
        "lang_ru": "Rus tili",
        'ai_main_menu': '🔙 Asosiy menyu',
        "lang_uz": "O'zbek tili",
        "no_debts": "Sizda qarzlar yo'q.",
        "cancel_btn": "❌ Bekor qilish",
        "your_debts": "Qarzlaringiz:",
        "debt_saved": "✅ Qarz saqlandi!\n\nAmalni tanlang:",
        "debt_closed": "✅ Qarz yopildi!\n\nAmalni tanlang:",
        "debt_deleted": "❌ Qarz o'chirildi!\n\nAmalni tanlang:",
        "debt_not_found": "Qarz topilmadi",
        "confirm_close": "Qarz yopildi deb belgilansinmi?",
        "export_excel": "📊 Excelga eksport",
        "confirm_del": "Qarz o'chirilsinmi?",
        "cancelled": "Amal bekor qilindi.",
        "back": "⬅️ Orqaga",
        "to_menu": "Menyuga",
        "to_list": "⬅️ Ro'yxatga",
        "edit": "✏️ O'zgartirish",
        "delete": "❌ O'chirish",
        "close": "Yopish",
        "extend": "Uzaytirish",
        "person": "📛 Kimdan qarz?:",
        "currency": "Valyutani tanlang:",
        "amount": "💰 Miqdor:",
        "amount_wrong": "Miqdor faqat raqam bo'lishi kerak!",
        "due": "📅 Qaytarish muddati (masalan):\n{suggest_date}",
        "due_wrong": "Sana formati (masalan):\n{suggest_date}",
        "direction": "🔁 Siz berdingizmi yoki oldingizmi?",
        "dir_gave": "Siz berdingiz",
        "dir_took": "Siz oldingiz",
        "comment": "📝 Izoh (ixtiyoriy):",
        "skip_comment": "O'tkazib yuborish",
        "date_format": "Sana formati: {suggest_date}",
        "date_changed": "Sana o'zgartirildi!",
        "changed": "O'zgartirildi!",
        "all_deleted": "🧹 Barcha qarzlar o'chirildi!\n\nAmalni tanlang:",
        "clear_all_confirm": "Barcha qarzlarni o'chirilsinmi?",
        "yes": "Ha",
        "no": "Yo'q",
        "notify_time": "Eslatma vaqti (masalan: 09:00):",
        "notify_wrong": "Vaqt formati noto'g'ri. Masalan: 09:00",
        "notify_set": "Eslatma vaqti o'rnatildi!\n",
        "edit_what": "Nimani o'zgartirasiz?",
        "debt_card": "{person} {amount} {currency}\nSana: {due}\nIzoh: {comment}\nEslatma vaqti: {notify_time}",
        "editfield_person": "Yangi ismni kiriting:",
        "editfield_amount": "Yangi miqdorini kiriting:",
        "editfield_currency": "Yangi valyutani kiriting (USD, UZS, EUR):",
        "editfield_due": "Yangi muddatni kiriting (masalan: {suggest_date}):",
        "editfield_comment": "Yangi izohni kiriting:",
        "currency_changed": "Valyuta o'zgartirildi!",
        "remind_close": "✅ Yopish",
        "remind_extend": "🔁 Uzaytirish",
        "remind_delete": "❌ O'chirish",
        "action_close": "✅ Yopish",
        "action_delete": "❌ O'chirish",
        "action_extend": "🔁 Uzaytirish",
        "direction_wrong": "\"gave\" yoki \"took\" kiriting!",
        "reminder_time": "Eslatma vaqti: {time}",
        "reminder_change": "Vaqtni o'zgartirish",
        "forward": "Oldinga ➡️",
        "backward": "⬅️ Orqaga",
        "db_error": "Ma'lumotlar bazasiga murojaat qilishda xatolik. Keyinroq urinib ko'ring.",
        "not_found_or_no_access": "Qarz topilmadi yoki ruxsat yo'q.",
        "delete_error": "Qarz o'chirishda xatolik.",
        "update_error": "Qarzni yangilashda xatolik.",
        "save_notify_error": "Eslatma vaqtini saqlashda xatolik.",
        "bad_request": "Xatolik: noto'g'ri so'rov formati.",
        "editfield_due_btn": "Sanani o'zgartirish",
        "editfield_person_btn": "Ismni o'zgartirish",
        "editfield_amount_btn": "Miqdorni o'zgartirish",
        "editfield_currency_btn": "Valyutani o'zgartirish",
        "editfield_comment_btn": "Izohni o'zgartirish",
        "how_to_use_btn": "ℹ️ Qanday foydalanish",
        "how_to_use_msg": "Botdan foydalanish bo'yicha batafsil yo'riqnomani ochish uchun pastdagi tugmani bosing.",
        "open_instruction": "Yo'riqnomani ochish",
        "continue_instruction": "Yo'riqnomani davom ettirish",
        "instruction_back": "⬅️ Orqaga",
        "debt_card_owed": "👤 Qarzdor: {person}\n💰 Qarzi: {amount} {currency}\n📅 To'lov muddati: {due}\n📝 Izoh: {comment}\n⏰ Eslatma vaqti: {notify_time}",
        "debt_card_owe": "👤 Sizning qarzingiz: {person}\n💰 Siz to'lashingiz kerak: {amount} {currency}\n📅 To'lov muddati: {due}\n📝 Izoh: {comment}\n⏰ Eslatma vaqti: {notify_time}",
        "daily_reminder_header": "⏰ Qarz eslatmasi:",
        "overdue": "⚠️ {days} kun kechiktirilgan",
        "due_today": "🔥 Muddat bugun tugaydi!",
        "due_in_days": "⏳ {days} kun qoldi",
        "debtor_name": "Qarzdor {person}",
        "creditor_name": "Kreditor {person}",
        "single_reminder": "⏰ Eslatma!\n\n{person} {amount} {currency} qaytarishi kerak\nMuddati: {due}",
        "multiple_reminders": "⏰ Sizda {count} ta qarz eslatmalari bor:",
        "process_interrupted": "Yaratish jarayonini davom ettirishni xohlaysizmi?",
        "continue_process": "📝 Davom etish",
        "cancel_and_menu": "🔙 Bekor qilish va menyuga",
        "date_in_past": "❌ Ko'rsatilgan sana o'tib ketgan. Iltimos, kelajakdagi sanani tanlang.",
        "process_cancelled": "❌ Jarayon bekor qilindi. Amal yakunlanmadi.",
        "continue_edit": "Tahrirlashni davom ettirish",
        "text_only_please": "Faqat tekst, iltimos",
        "export_excel_btn": "📊 Excelga eksport",
        "export_loading": "⏳ Eksport tayyorlanmoqda...",
        "export_success_caption": "📊 Eksport muvaffaqiyatli tugallandi!\n\n📝 Fayl quyidagilarni o'z ichiga oladi:\n• Barcha faol qarzlar\n• Qarzdorlar/kreditorlar haqida ma'lumot\n• Summalar va valyutalar\n• Sanalar va sharhlar\nhttps://telegra.ph/Kak-ispravit-oshibku-pri-otkrytii-fajla-Exel-10-03",
        "export_error": "❌ Ma'lumotlarni eksport qilishda xatolik. Keyinroq urinib ko'ring.",
        "back_main_btn": "🏠 Asosiy menyu",
        "export_col_id": "ID",
        "export_col_person": "Ism",
        "export_col_amount": "Miqdor",
        "export_col_currency": "Valyuta",
        "export_col_type": "Qarz turi",
        "export_col_date": "Yaratilgan sana",
        "export_col_due": "Qarzni yopish muddati",
        "export_col_comment": "Izoh",
        "export_col_status": "Holat",
        "export_col_created": "Yaratilgan",
        "export_type_owe": "Siz berdingiz",
        "export_type_owed": "Siz oldingiz",
        "export_status_closed": "Yopiq",
        "export_status_active": "Faol",
        "export_sheet_name": "Qarzlar",
        "start_add": "Eslatma matnini kiriting:",
        "ask_due": "Sana va vaqtni kiriting (format: 2025-09-22 10:00)",
        "bad_due": "❌ Noto'g'ri format. Qayta urinib ko'ring: 2025-09-22 10:00",
        "ask_repeat": "Takrorlash rejimini tanlang:",
        "created": "✅ Eslatma yaratildi!",
        "no_reminders": "Sizda faol eslatmalar yo'q.",
        "list_title": "📋 Sizning eslatmalaringiz:",
        "del_usage": "Foydalanish: /del_reminder <id>",
        "deleted": "🗑 Eslatma {id} o'chirildi.",
        "reminder_message": "Eslatma: {reminder}",
        "currency_message": "{base}/{quote} = {rate:.2f}",

        # --- Repeat buttons ---
        "repeat_none": "Takrorlanmasin",
        "repeat_daily": "Har kuni",
        "repeat_monthly": "Har oy",
        "debts_btn": "Qarzlar",
        "currency_btn": "Valyutalar kursi",
        "my_reminders_btn": "📋 Mening eslatmalarim",
        "add_reminder_btn": "➕ Eslatma qo'shish",
        "reminder_status_active": "✅ Qarz eslatmasi soat {time} da",
        "reminder_status_currency_morning": "✅ Valyutalar kursi har kuni soat 7:00",
        "reminder_status_currency_evening": "✅ Valyutalar kursi har kuni soat 17:00",
        "reminder_status_disabled": "❌ Eslatmalar o'chirilgan",
        "menu.debts_off": "❌ Qarz eslatmalari o'chirilgan",
        "menu.currency_on": "✅ Valyuta kursi har kuni soat {time} da",
        "menu.currency_off": "❌ Valyuta kursi eslatmalari o'chirilgan",

        # Статусы в главном меню Напоминаний
        "debt_reminder_status": "Qarzlar eslatmasi (sizning vaqtingiz)",
        "currency_reminder_status": "Kurs har kuni soat 7:00da",

        # Подменю «Напоминания о долгах»
        "debt_reminders_text": "Avtomatik qarz eslatmasi (3 kun oldin, agar qarz muddati tugagan bo'lsa har kuni).",
        "enable_debt": "⏰ Eslatmalarni yoqish",
        "disable_debt": "❌ Eslatmalarni o'chirish",
        "set_time": "⚙️ Vaqtini o'zgartirish",

        # Подменю «Напоминания о курсе валют»
        "currency_reminders_text": "Misol uchun dollar kursi har kuni soat 7:00.",
        "enable_currency_morning": "⏰ Ertalabgi valyutalar kursini yoqish (7:00)",
        "enable_currency_evening": "⏰ Kechki valyutalar kursini yoqish (17:00)",
        "disable_currency": "❌ Valyutalar kursini o'chirish",
        'currency_error': '❌ Valyuta kurslarini olishda xatolik yuz berdi. Iltimos, keyinroq qayta urinib ko ring.',
        'currency_format_error': '❌ Valyuta kurslarini formatlashda xatolik yuz berdi.',
        'debts_list': '📥 Qarzlar',
        'debt_reminders': '📥 Qarzlar',
        'currency_reminders': '💱 Valyuta kursi',
        'add_reminder': '➕ Eslatma qo shish',
        'my_reminders': '📋 Mening eslatmalarim',
        'enable_reminders': '⏰ Eslatmalarni yoqish',
        'disable_reminders': '❌ Eslatmalarni o chirish',
        'setup_time': '⚙️ Vaqtni sozlash',
        'enable_morning_rates': '⏰ Ertalab valyuta kursini yoqish',
        'enable_evening_rates': '⏰ Kechki valyuta kursini yoqish',
        'disable_currency_rates': '❌ Valyuta kursini o chirish',
        'no_repeat': '❌ Yo q',
        'daily_repeat': '📅 Har kuni',
        'monthly_repeat': '📆 Har oy',
        'reminders_list': 'Eslatmalar',
        'edit_reminder_datetime': 'Sanani va vaqtini o zgartirish',
        'edit_reminder_repeat': 'Takrorlashni o zgartirish',
        'reminder_text_prompt': 'Nima haqida eslatma?',
        'reminder_datetime_prompt': 'Qachon eslatma? (masalan: 25.09 soat 19:00)',
        'reminder_repeat_prompt': 'Eslatmani takrorlash kerakmi?',
        'your_reminders': 'Sizning eslatmalaringiz:',
        'ai_debt_input_hint': (
            "Ma'lumotlarni erkin matn bilan kiriting:\n"
            "- yo'nalish ('men qarzdorman' yoki 'menga qarzdor')\n"
            "- qarzdor (ism/yoki nom)\n"
            "- summa va valyuta (masalan: 250 USD)\n"
            "- muddat (YYYY-MM-DD)\n"
            "- izoh (majburiy emas)"
        ),
    }
}


async def tr(user_id: int, key: str, **kwargs) -> str:
    """Получить переведенный текст для пользователя"""
    try:
        user_data = await get_user_data(user_id)
        lang = user_data.get('lang', 'ru')
        text = LANGS[lang].get(key, key)
        return text.format(**kwargs) if kwargs else text
    except Exception:
        # В случае ошибки возвращаем русский текст
        text = LANGS['ru'].get(key, key)
        return text.format(**kwargs) if kwargs else text